#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "optparse"

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: mt-server [options]"

  opts.on("--project-root DIR", "Root of the project to test (default: pwd)") do |v|
    options[:project_root] = v
  end

  opts.on("--test-path GLOB", "Test file glob (repeatable)") do |v|
    (options[:test_paths] ||= []) << v
  end

  opts.on("--load-path PATH", "Add to $LOAD_PATH (repeatable)") do |v|
    (options[:load_paths] ||= []) << v
  end

  opts.on("--uri-file PATH", "URI file location") do |v|
    options[:uri_file] = v
  end

  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end

  opts.on("-V", "--version", "Show version") do
    require "minitest/jruby/server"
    puts "mt-server #{Minitest::Jruby::Server::VERSION}"
    exit
  end
end.parse!

require "minitest"
require "minitest/test"
require "minitest/jruby/server"

config = Minitest::Jruby::Server::Config.new(**options.compact)

# Boot
$stderr.puts "[mt-server] Booting on #{RUBY_ENGINE} #{RUBY_ENGINE_VERSION}..."
boot_start = Process.clock_gettime(Process::CLOCK_MONOTONIC)

loader = Minitest::Jruby::Server::TestLoader.new(config: config)
loader.setup_load_path!
loader.load_tests!

# JRuby requires seed set before runnable_methods
Minitest.seed = 0
srand 0

boot_time = Process.clock_gettime(Process::CLOCK_MONOTONIC) - boot_start
suites = loader.loaded_suites

$stderr.puts "[mt-server] Boot complete in %.4fs" % boot_time
$stderr.puts "[mt-server] #{suites.size} suites, #{suites.flat_map { |s| s.methods_matching(/^test_/) }.size} methods"

# Serve
daemon = Minitest::Jruby::Server::Daemon.new
server = Minitest::Jruby::Server::Server.new(daemon: daemon, config: config)

$stderr.puts "[mt-server] Listening at #{server.uri}"
$stderr.puts "[mt-server] URI file: #{config.uri_file}"
$stderr.puts "[mt-server] Ctrl-C to stop"

server.start
